# Generated by Django 5.1.4 on 2024-12-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0003_alter_hotel_hotel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
    ]
